spring:
  datasource:
    url: jdbc:mysql://mysql:3306/e-commerce?useSSL=false&allowPublicKeyRetrieval=true
    username: ecommerce_user
    password: ecommerce_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngochuymail25@gmail.com
    password: jwrs ymuu aote jbsv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  prefix: api/v1

jwt:
  secret: EQOIAUgMdB/GxPmYT+uew/HLvOkYDOrAo3ihcFynD+Y=
  expiration: 2592000
  expiration-refresh-token: 5184000

# Actuator for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


